# Generated by Django 4.2 on 2023-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='Description',
            field=models.TextField(max_length=500),
        ),
    ]
