# Generated by Django 4.2 on 2023-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_cards_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='Sub Title',
            new_name='SubTitle',
        ),
        migrations.AlterField(
            model_name='journal',
            name='Description',
            field=models.TextField(max_length=500),
        ),
    ]
