# Generated by Django 4.2 on 2023-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_sub_title_cards_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='Image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
